// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Execute(arg1, arg2, arg3) {
  return window['go']['rconclient']['RconClient']['Execute'](arg1, arg2, arg3);
}
