// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSteamProfileURL(arg1:string):Promise<void>;

export function InitApp():Promise<void>;

export function OpenInBrowser(arg1:string):Promise<void>;
