// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSteamProfileURL(arg1) {
  return window['go']['main']['App']['GetSteamProfileURL'](arg1);
}

export function InitApp() {
  return window['go']['main']['App']['InitApp']();
}

export function OpenInBrowser(arg1) {
  return window['go']['main']['App']['OpenInBrowser'](arg1);
}
