// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Dispose() {
  return window['go']['dedicatedserver']['DedicatedServer']['Dispose']();
}

export function DownloadDedicatedServer() {
  return window['go']['dedicatedserver']['DedicatedServer']['DownloadDedicatedServer']();
}

export function Init(arg1) {
  return window['go']['dedicatedserver']['DedicatedServer']['Init'](arg1);
}

export function IsRunning() {
  return window['go']['dedicatedserver']['DedicatedServer']['IsRunning']();
}

export function MonitorServerProcess() {
  return window['go']['dedicatedserver']['DedicatedServer']['MonitorServerProcess']();
}

export function ReadConfig() {
  return window['go']['dedicatedserver']['DedicatedServer']['ReadConfig']();
}

export function Restart() {
  return window['go']['dedicatedserver']['DedicatedServer']['Restart']();
}

export function Start() {
  return window['go']['dedicatedserver']['DedicatedServer']['Start']();
}

export function Stop() {
  return window['go']['dedicatedserver']['DedicatedServer']['Stop']();
}

export function Update() {
  return window['go']['dedicatedserver']['DedicatedServer']['Update']();
}

export function WriteConfig(arg1) {
  return window['go']['dedicatedserver']['DedicatedServer']['WriteConfig'](arg1);
}
