// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function Dispose():Promise<void>;

export function DownloadDedicatedServer():Promise<void>;

export function Init(arg1:context.Context):Promise<void>;

export function MonitorServerProcess():Promise<void>;

export function ReadConfig():Promise<string>;

export function Restart():Promise<void>;

export function Start():Promise<void>;

export function Stop():Promise<void>;

export function WriteConfig(arg1:string):Promise<void>;
