// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckCount() {
  return window['go']['backupsmanager']['BackupManager']['CheckCount']();
}

export function CreateBackup() {
  return window['go']['backupsmanager']['BackupManager']['CreateBackup']();
}

export function Delete(arg1) {
  return window['go']['backupsmanager']['BackupManager']['Delete'](arg1);
}

export function Dispose() {
  return window['go']['backupsmanager']['BackupManager']['Dispose']();
}

export function GetBackupsList() {
  return window['go']['backupsmanager']['BackupManager']['GetBackupsList']();
}

export function Init(arg1) {
  return window['go']['backupsmanager']['BackupManager']['Init'](arg1);
}

export function Open(arg1) {
  return window['go']['backupsmanager']['BackupManager']['Open'](arg1);
}

export function Restore(arg1) {
  return window['go']['backupsmanager']['BackupManager']['Restore'](arg1);
}

export function Start(arg1, arg2) {
  return window['go']['backupsmanager']['BackupManager']['Start'](arg1, arg2);
}

export function Stop() {
  return window['go']['backupsmanager']['BackupManager']['Stop']();
}
