// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backupsmanager} from '../models';
import {context} from '../models';

export function CheckCount():Promise<void>;

export function CreateBackup():Promise<void>;

export function Delete(arg1:string):Promise<void>;

export function Dispose():Promise<void>;

export function GetBackupsList():Promise<Array<backupsmanager.Backup>>;

export function Init(arg1:context.Context):Promise<void>;

export function Open(arg1:string):Promise<void>;

export function Restore(arg1:string):Promise<void>;

export function Start(arg1:number,arg2:number):Promise<void>;

export function Stop():Promise<void>;
