// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadFile'](arg1, arg2, arg3);
}

export function InitApp() {
  return window['go']['main']['App']['InitApp']();
}

export function OpenInBrowser(arg1) {
  return window['go']['main']['App']['OpenInBrowser'](arg1);
}

export function OpenLogs() {
  return window['go']['main']['App']['OpenLogs']();
}

export function SaveLog(arg1) {
  return window['go']['main']['App']['SaveLog'](arg1);
}
