// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function InitApp():Promise<void>;

export function OpenInBrowser(arg1:string):Promise<void>;

export function OpenLogs():Promise<void>;

export function SaveLog(arg1:string):Promise<void>;
